### ISSUE TITLE
Anyone managed to run this plugin in NS 8 with Angular 14

### ISSUE THREAD

**Issue by harfyt** [shripalsoni04/ns-ng-webview-interface-demo#8]
Hi, I found this plugin that I would like to use but as I recon it is abandoned.
I tried to use it with NS 8.3.0 in Angular project 14.2.0 and I getting the following error while initializing the webview

```
chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0
  chromium: [ERROR:filesystem_posix.cc(89)] stat /data/user/0/org.nativescript.employeeapp/cache/WebView/Crashpad: No such file or directory (2)
  chromium: [ERROR:filesystem_posix.cc(62)] mkdir /data/user/0/org.nativescript.employeeapp/cache/WebView/Crashpad: No such file or directory (2)
  System.err: An uncaught Exception occurred on "main" thread.
  System.err: Calling js method onCreateView failed
  System.err: TypeError: Cannot read property 'once' of undefined
  System.err:
  System.err: StackTrace:
  System.err: _handleEvent(file: src\webpack:\employee-app\node_modules\@nativescript\core\data\observable\index.js:226:0)
  System.err:   at notify(file: src\webpack:\employee-app\node_modules\@nativescript\core\data\observable\index.js:216:0)
...
```

Here is my initializing code:

```
private setupWebViewInterface() {
		let webView: WebView = this.webView.nativeElement;

		this.oMapWebViewInterface = new webViewInterfaceModule.WebViewInterface(webView, '~/app/www/index.html');

		// loading languages in dropdown, on load of webView.
		webView.on(WebView.loadFinishedEvent, (args: LoadEventData) => {
			if (!args.error) {
				console.log('WEB VIEW LOADED!')
				this.loadPointsInWebView();
			}
		});

		this.listenMapWebViewEvents();
	}
```

And here is my folder containing the html 
`src\app\www\index.html`

![image](https://github.com/shripalsoni04/ns-ng-webview-interface-demo/assets/2162094/d490f204-728a-4193-a414-4c6c99161e45)
